baseURL: 'https://syntax-cauliflower.netlify.app/'
languageCode: en-us
title: Ben Basten
theme: paper

menu:
    main:
        - name: Archive
          url: archives
          weight: 1
        - name: About me
          url: about-me
          weight: 3
        - name: Portfolio
          url: projects/
          weight: 2
        - name: Contact
          url: contact
          weight: 4
          
taxonomies:
    tag: tags
    technology: technologies